services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:latest"
    # ZITADEL_MASTERKEY: 'SAcD5TY0QPp89ip28bZPfEA5WDxqmobx' # run tr -dc A-Za-z0-9 </dev/urandom | head -c 32
    command: "start-from-init --config /example-zitadel-config.yaml --config /example-zitadel-secrets.yaml --steps /example-zitadel-init-steps.yaml --masterkey $${MASTERKEY} --tlsMode disabled"
    environment:
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: $${ADMIN_USERNAME}
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: $${ADMIN_PASSWORD}
      ZITADEL_EXTERNALSECURE: true

    depends_on:
      db:
        condition: "service_healthy"
    ports:
      - "8090:8080"
    volumes:
      - "./example-zitadel-config.yaml:/example-zitadel-config.yaml:ro"
      - "./example-zitadel-secrets.yaml:/example-zitadel-secrets.yaml:ro"
      - "./example-zitadel-init-steps.yaml:/example-zitadel-init-steps.yaml:ro"
  db:
    restart: "always"
    image: postgres:16-alpine
    environment:
      PGUSER: $${PG_USER}
      POSTGRES_PASSWORD: $${PG_PASSWORD}
    networks:
      - "zitadel"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "$${PG_USER}" ]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"

networks:
  zitadel:
